spring:
  application:
    name: api-gateway
server:
  port: 9004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: eureka-consumer-hystrix